'use strict';

const { default: makeWASocket, DisconnectReason } = require('@whiskeysockets/baileys');
const { Boom } = require('@hapi/boom');
const qrcode = require('qrcode');
const db = require('../database/db');
const useTursoAuthState = require('./baileys_auth');
const pino = require('pino');

let sock = null;
let currentQR = null;
let connectionState = 'connecting';
let userPhone = null;

// Bumped every time a new socket is created. Event handlers from an older
// socket capture the generation they belong to and become a no-op once a
// newer socket takes over — this prevents a delayed/async 'connection.update'
// callback from a stale (logged-out) socket from wiping out the fresh QR
// generated by the new socket right after a manual logout.
let socketGeneration = 0;

// Allow injecting message handler
let onMessageReceived = null;

function setMessageHandler(handler) {
  onMessageReceived = handler;
}

let isStarting = false;
let reconnectTimer = null;

async function startBaileys() {
  // امنع تشغيل أكتر من instance في نفس الوقت
  if (isStarting) {
    console.log('[Baileys] startBaileys already in progress, skipping duplicate call.');
    return;
  }
  isStarting = true;

  // نضف أي timer reconnect معلق
  if (reconnectTimer) {
    clearTimeout(reconnectTimer);
    reconnectTimer = null;
  }

  // اقفل ونضف السوكت القديم تمامًا قبل ما تفتح واحد جديد
  if (sock) {
    try {
      sock.ev.removeAllListeners();
      sock.end(new Error('Restarting connection'));
    } catch (e) {
      console.error('[Baileys] Error cleaning up old socket:', e.message);
    }
    sock = null;
  }

  // كل استدعاء جديد لـ startBaileys بياخد رقم جيل جديد. أي event handler
  // من سوكت قديم هيتأكد إن الجيل بتاعه لسه هو الحالي قبل ما يعدّل أي حالة.
  socketGeneration += 1;
  const myGeneration = socketGeneration;

  try {
    const { state, saveCreds } = await useTursoAuthState(db);

    sock = makeWASocket({
      auth: state,
      printQRInTerminal: false,
      logger: pino({ level: 'silent' }),
      browser: ['DopaConfirm', 'Chrome', '1.0.0'],
      generateHighQualityLinkPreview: true,
    });

    sock.ev.on('creds.update', saveCreds);

  sock.ev.on('connection.update', async (update) => {
    // هاندلر جاي من سوكت قديم اتلغى؟ متعملش أي حاجة خالص
    if (myGeneration !== socketGeneration) return;

    const { connection, lastDisconnect, qr } = update;
    
    if (qr) {
      const qrDataUrl = await qrcode.toDataURL(qr);
      if (myGeneration !== socketGeneration) return; // تأكد تاني بعد الـ await (ممكن يبقى فيه سوكت أحدث اتعمل أثناء توليد الصورة)
      currentQR = qrDataUrl;
      connectionState = 'qr';
    }

    if (connection === 'close') {
      const error = lastDisconnect?.error instanceof Boom ? lastDisconnect.error : null;
      const statusCode = error?.output?.statusCode;
      const reason = DisconnectReason[statusCode] || 'unknown';

      console.log(`[Baileys] Connection closed. statusCode: ${statusCode} | reason: ${reason}`);

      if (statusCode === DisconnectReason.loggedOut) {
        // 401 — الرقم اتمسح من الأجهزة المرتبطة
        console.log('[Baileys] LOGGED OUT — clearing session, will show fresh QR.');
        currentQR = null;
        connectionState = 'disconnected';
        await db.getDb().execute('DELETE FROM whatsapp_auth');
        if (myGeneration !== socketGeneration) return;
        // ابدأ من الأول فوراً عشان يولد QR جديد
        if (!reconnectTimer) {
          reconnectTimer = setTimeout(() => { reconnectTimer = null; startBaileys(); }, 1500);
        }

      } else if (statusCode === DisconnectReason.connectionReplaced) {
        // 440 — نسخة تانية اتصلت بنفس الـ session
        // (Railway بيشغل container جديد وقديم في نفس الوقت لحظة الـ redeploy)
        // الحل: استنى 30 ثانية عشان الـ container القديم يموت وبعدين اتصل
        console.warn('[Baileys] connectionReplaced — another instance is active. Waiting 30s before retry...');
        connectionState = 'reconnecting';
        if (!reconnectTimer) {
          reconnectTimer = setTimeout(() => { reconnectTimer = null; startBaileys(); }, 30000);
        }

      } else {
        // restartRequired, connectionClosed, timedOut, etc. — reconnect بعد 5 ثواني
        connectionState = 'reconnecting';
        if (!reconnectTimer) {
          reconnectTimer = setTimeout(() => { reconnectTimer = null; startBaileys(); }, 5000);
        }
      }

    } else if (connection === 'open') {
      console.log('[Baileys] Connected to WhatsApp successfully!');
      currentQR = null;
      connectionState = 'connected';
      userPhone = sock.user.id.split(':')[0];
    }
  });

  sock.ev.on('messages.upsert', async (m) => {
    if (m.type === 'notify') {
      for (const msg of m.messages) {
        if (!msg.key.fromMe && msg.message) {
          let sender = msg.key.remoteJid; // ممكن تيجي بصيغة LID: 103843853529241@lid بدل رقم التليفون

          // لو الـ JID جاي بصيغة LID، حوله لرقم التليفون الحقيقي (PN) عشان نلاقي الـ session بيه
          if (sender && sender.endsWith('@lid')) {
            let resolvedPn = msg.key.remoteJidAlt || null;
            if (!resolvedPn) {
              try {
                resolvedPn = await sock.signalRepository.lidMapping.getPNForLID(sender);
              } catch (e) {
                console.error('[Baileys] Error resolving LID to PN:', e.message);
              }
            }
            if (resolvedPn) {
              console.log(`[Baileys] Resolved LID ${sender} → PN ${resolvedPn}`);
              sender = resolvedPn;
            } else {
              console.warn(`[Baileys] ⚠️ Could not resolve LID ${sender} to a phone number — session lookup will likely fail.`);
            }
          }

          let text = '';
          if (msg.message.conversation) {
            text = msg.message.conversation;
          } else if (msg.message.extendedTextMessage) {
            text = msg.message.extendedTextMessage.text;
          } else if (msg.message.pollCreationMessage) {
              text = msg.message.pollCreationMessage.name;
          } else if (msg.message.pollUpdateMessage) {
            const { decryptPollVote, jidNormalizedUser } = require('@whiskeysockets/baileys');
            const crypto = require('crypto');
            try {
                const pollKey = msg.message.pollUpdateMessage.pollCreationMessageKey;
                const pollMsgId = pollKey.id;
                console.log(`[Baileys] Poll vote received — pollMsgId: ${pollMsgId} | fromMe: ${pollKey.fromMe} | participant: ${pollKey.participant} | voterJid: ${msg.key.remoteJid}`);
                const secretBase64 = await db.getPollSecret(pollMsgId);
                if (secretBase64) {
                    // واتساب بقت تشفر تصويتات الـ poll بصيغة LID مش PN دايمًا، فمفيش طريقة مضمونة
                    // نعرف بيها الصيغة الصح مقدمًا. الحل الموثق رسميًا من Baileys: نجرب كل التركيبات
                    // الممكنة (LID/PN) لحد ما توحدة تفك التشفير بنجاح.
                    const pollEncKey = Buffer.from(secretBase64, 'base64');

                    const meIdNormalised = jidNormalizedUser(sock.user.id);
                    // sock.user.lid بييجي ومعاه device suffix (مثال: 123456:7@lid) لازم يتشال
                    const meLidNormalised = sock.user.lid ? jidNormalizedUser(sock.user.lid) : null;

                    const creatorPnJid = pollKey.fromMe
                        ? meIdNormalised
                        : (pollKey.participant || msg.key.remoteJid);
                    const creatorLidJid = (pollKey.fromMe && meLidNormalised) ? meLidNormalised : creatorPnJid;

                    const voterPnJid = msg.key.remoteJid;
                    const voterLidJid = msg.key.remoteJidAlt || msg.key.senderLid || voterPnJid;

                    const jidCombos = [
                        [creatorLidJid, voterPnJid],
                        [creatorLidJid, voterLidJid],
                        [creatorPnJid, voterPnJid],
                        [creatorPnJid, voterLidJid],
                    ];

                    let decrypted = null;
                    for (const [pollCreatorJid, voterJid] of jidCombos) {
                        if (!pollCreatorJid || !voterJid) continue;
                        try {
                            decrypted = decryptPollVote(msg.message.pollUpdateMessage.vote, {
                                pollCreatorJid,
                                pollMsgId,
                                pollEncKey,
                                voterJid,
                            });
                            if (decrypted) {
                                console.log(`[Baileys] ✅ Poll decrypted using combo creator=${pollCreatorJid} voter=${voterJid}`);
                                break;
                            }
                        } catch (innerErr) {
                            // جرب التركيبة الجاية
                        }
                    }

                    if (decrypted && decrypted.selectedOptions && decrypted.selectedOptions.length > 0) {
                        const hashSelected = Buffer.from(decrypted.selectedOptions[0]).toString('hex');
                        const opt1 = '✅ تأكيد الطلب';
                        const opt2 = '❌ تعديل أو إلغاء';
                        const h1 = crypto.createHash('sha256').update(opt1).digest('hex');
                        const h2 = crypto.createHash('sha256').update(opt2).digest('hex');
                        if (hashSelected === h1) text = opt1;
                        else if (hashSelected === h2) text = opt2;
                        console.log(`[Baileys] Poll selected option: "${text}"`);
                    } else {
                        console.log('[Baileys] ⚠️ All JID combos failed to decrypt poll vote');
                    }
                } else {
                    console.log(`[Baileys] No poll secret found for pollMsgId: ${pollMsgId}`);
                }
            } catch(e) {
                console.error('[Baileys] Error decrypting poll:', e.message);
            }
          }


          if (text && onMessageReceived) {
            onMessageReceived(sender, text);
          }
        }
      }
    }
  });

  isStarting = false;
  } catch (err) {
    console.error('[Baileys] Fatal error during startBaileys:', err.message);
    isStarting = false;
    // حاول تاني بعد شوية بدل ما تفضل عالقة
    if (!reconnectTimer) {
      reconnectTimer = setTimeout(() => {
        reconnectTimer = null;
        startBaileys();
      }, 5000);
    }
  }
}

function getConnectionStatus() {
  return {
    state: connectionState,
    qr: currentQR,
    user: userPhone
  };
}

async function sendWhatsAppMessage(phone, text, withImage = false, imageKey = 'WHATSAPP_MESSAGE_IMAGE_BASE64', rawImageBase64 = null) {
  if (!sock || connectionState !== 'connected') {
      console.error('[Baileys] Not connected. Cannot send message.');
      return false;
  }
  try {
      const jid = phone.includes('@') ? phone : `${phone}@s.whatsapp.net`;
      let imageBase64 = rawImageBase64;
      if (withImage && !imageBase64) {
          imageBase64 = await db.getSetting(imageKey);
      }
      if (imageBase64 && imageBase64.length > 100) {
          const buffer = Buffer.from(imageBase64, 'base64');
          await sock.sendMessage(jid, { image: buffer, caption: text });
      } else {
          await sock.sendMessage(jid, { text });
      }
      return true;
  } catch (err) {
      console.error('[Baileys] Send error:', err);
      return false;
  }
}

async function sendWhatsAppPoll(phone, question, options) {
  if (!sock || connectionState !== 'connected') {
      console.error('[Baileys] Not connected. Cannot send poll.');
      return false;
  }
  try {
      const jid = phone.includes('@') ? phone : `${phone}@s.whatsapp.net`;
      
      const sentMsg = await sock.sendMessage(jid, {
        poll: {
          name: question,
          values: options,
          selectableCount: 1
        }
      });
      
      if (sentMsg?.message?.messageContextInfo?.messageSecret) {
         const secretBase64 = Buffer.from(sentMsg.message.messageContextInfo.messageSecret).toString('base64');
         await db.insertPollSecret(sentMsg.key.id, secretBase64);
         console.log(`[Baileys] Poll secret saved for messageId: ${sentMsg.key.id}`);
      } else {
         console.warn(`[Baileys] ⚠️ No messageSecret found on sent poll! messageId: ${sentMsg?.key?.id}`);
      }
      
      return true;
  } catch (err) {
      console.error('[Baileys] Send poll error:', err);
      return false;
  }
}

async function logoutBaileys() {
    if (sock) {
        try {
            await Promise.race([
                sock.logout(),
                new Promise(resolve => setTimeout(resolve, 2000))
            ]);
        } catch(e) {}
        try {
            sock.ev.removeAllListeners();
            sock.end(new Error('Logout forced'));
        } catch(e) {}
        sock = null;
    }
    if (reconnectTimer) {
        clearTimeout(reconnectTimer);
        reconnectTimer = null;
    }
    await db.getDb().execute("DELETE FROM whatsapp_auth");
    connectionState = 'disconnected';
    currentQR = null;
    isStarting = false;
    await startBaileys();
}

// ─── Wait Until Connected ─────────────────────────────────────────────────────
// بتستنى الاتصال يتم لمدة maxMs مللي ثانية — بتشيك كل checkInterval ms
// لو اتصل ترجع true، لو انتهى الوقت ترجع false

async function waitUntilConnected(maxMs = 20000, checkInterval = 500) {
  if (connectionState === 'connected') return true;
  const start = Date.now();
  return new Promise((resolve) => {
    const timer = setInterval(() => {
      if (connectionState === 'connected') {
        clearInterval(timer);
        resolve(true);
      } else if (Date.now() - start >= maxMs) {
        clearInterval(timer);
        resolve(false);
      }
    }, checkInterval);
  });
}

module.exports = {
  startBaileys,
  getConnectionStatus,
  waitUntilConnected,
  sendWhatsAppMessage,
  sendWhatsAppPoll,
  logoutBaileys,
  setMessageHandler
};
